import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Text, View } from 'react-native';
import { api, apiErrorMessage, authHeaders } from '../../lib/api';
import { PIN, User } from '../../types/entities';
import {
  Banner,
  Button,
  Divider,
  FieldLabel,
  Input,
  SectionCard,
  SubtleText,
} from '../common/ui';

interface PinManagementProps {
  token: string;
  user: User;
}

const weakPins = new Set([
  '0000',
  '1111',
  '1234',
  '4321',
  '1212',
  '9999',
  '2580',
  '2222',
  '3333',
]);

export const PinManagement = ({ token, user }: PinManagementProps) => {
  const [pins, setPins] = useState<PIN[]>([]);
  const [pin, setPin] = useState('');
  const [label, setLabel] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(false);

  const needsPinInput = user.role !== 'guest';

  const pinFeedback = useMemo(() => {
    if (!pin) {
      return '';
    }

    if (!/^\d{4,8}$/.test(pin)) {
      return 'PIN should be 4-8 digits.';
    }

    if (weakPins.has(pin)) {
      return 'Weak PIN. Pick a less predictable one.';
    }

    return '';
  }, [pin]);

  const loadPins = useCallback(async () => {
    setLoading(true);
    try {
      const response = await api.get<PIN[]>(`/users/${user.id}/pins`, {
        headers: authHeaders(token),
      });
      setPins(response.data);
    } catch (nextError) {
      setError(apiErrorMessage(nextError, 'Failed to fetch PINs.'));
    } finally {
      setLoading(false);
    }
  }, [token, user.id]);

  useEffect(() => {
    loadPins();
  }, [loadPins]);

  const addPin = async () => {
    setError('');
    setSuccess('');

    if (needsPinInput && pinFeedback) {
      setError(pinFeedback);
      return;
    }

    try {
      await api.post(
        '/pins',
        {
          user_id: user.id,
          label: label.trim() || 'PIN',
          pin: needsPinInput ? pin.trim() : undefined,
        },
        { headers: authHeaders(token) }
      );

      setPin('');
      setLabel('');
      setSuccess('PIN added.');
      await loadPins();
    } catch (nextError) {
      setError(apiErrorMessage(nextError, 'Failed to add PIN.'));
    }
  };

  const deletePin = (pinId: number) => {
    Alert.alert('Delete PIN', 'Delete this PIN?', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          setError('');
          setSuccess('');
          try {
            await api.delete(`/pins/${pinId}`, {
              headers: authHeaders(token),
            });
            setSuccess('PIN deleted.');
            await loadPins();
          } catch (nextError) {
            setError(apiErrorMessage(nextError, 'Failed to delete PIN.'));
          }
        },
      },
    ]);
  };

  return (
    <SectionCard title={`PINs: ${user.name}`}>
      <View style={{ gap: 6 }}>
        <FieldLabel>Label</FieldLabel>
        <Input value={label} onChangeText={setLabel} placeholder="Main keypad" />
      </View>

      {needsPinInput ? (
        <View style={{ gap: 6 }}>
          <FieldLabel>PIN</FieldLabel>
          <Input
            keyboardType="number-pad"
            secureTextEntry
            value={pin}
            onChangeText={setPin}
            placeholder="4-8 digits"
          />
          {pinFeedback ? <Banner type="info" text={pinFeedback} /> : null}
        </View>
      ) : (
        <SubtleText>Guest PIN auto-generated by backend.</SubtleText>
      )}

      <Button
        title="Add PIN"
        onPress={addPin}
        disabled={!label.trim() || (needsPinInput && !pin.trim())}
      />

      {error ? <Banner type="error" text={error} /> : null}
      {success ? <Banner type="success" text={success} /> : null}

      <Divider />
      {pins.length === 0 ? (
        <SubtleText>{loading ? 'Loading PINs...' : 'No PINs found.'}</SubtleText>
      ) : (
        <View style={{ gap: 8 }}>
          {pins.map((item) => (
            <View
              key={item.id}
              style={{
                borderWidth: 1,
                borderColor: '#d2dbf0',
                borderRadius: 10,
                padding: 10,
                gap: 6,
              }}
            >
              <Text style={{ fontWeight: '700' }}>{item.label}</Text>
              <SubtleText>Created: {new Date(item.created_at).toLocaleString()}</SubtleText>
              <Button title="Delete" variant="danger" onPress={() => deletePin(item.id)} />
            </View>
          ))}
        </View>
      )}
    </SectionCard>
  );
};
